export interface LanguageOption {
    label: string,
    value: string
}

export interface Languages {
    [key: string]: LanguageOption[]
}

export const languages: Languages = {
    baidu: [
        { label: "Auto", value: "auto" },
        { label: "中文", value: "zh" },
        { label: "English", value: "en" },
        { label: "粵語", value: "yue" },
        { label: "文言文", value: "wyw" },
        { label: "日本語", value: "jp" },
        { label: "한국어", value: "kor" },
        { label: "Français", value: "fra" },
        { label: "Español", value: "spa" },
        { label: "ภาษาไทย", value: "th" },
        { label: "العربية", value: "ara" },
        { label: "Русский", value: "ru" },
        { label: "Português", value: "pt" },
        { label: "Deutsch", value: "de" },
        { label: "Italiano", value: "it" },
        { label: "Ελληνικά", value: "el" },
        { label: "Nederlands", value: "nl" },
        { label: "Polski", value: "pl" },
        { label: "Български", value: "bul" },
        { label: "Eesti", value: "est" },
        { label: "Dansk", value: "dan" },
        { label: "Suomi", value: "fin" },
        { label: "Čeština", value: "cs" },
        { label: "Română", value: "rom" },
        { label: "Slovenščina", value: "slo" },
        { label: "Svenska", value: "swe" },
        { label: "Magyar", value: "hu" },
        { label: "繁體中文", value: "cht" },
        { label: "Tiếng Việt", value: "vie" }
    ],
    youdao: [
        { label: "العربية", value: "ar" },
        { label: "Deutsch", value: "de" },
        { label: "English", value: "en" },
        { label: "Español", value: "es" },
        { label: "Français", value: "fr" },
        { label: "हिन्दी", value: "hi" },
        { label: "Bahasa Indonesia", value: "id" },
        { label: "Italiano", value: "it" },
        { label: "日本語", value: "ja" },
        { label: "한국어", value: "ko" },
        { label: "Nederlands", value: "nl" },
        { label: "Português", value: "pt" },
        { label: "Русский", value: "ru" },
        { label: "ภาษาไทย", value: "th" },
        { label: "Tiếng Việt", value: "vi" },
        { label: "简体中文", value: "zh-CHS" },
        { label: "繁體中文", value: "zh-CHT" },
        { label: "Afrikaans", value: "af" },
        { label: "አማርኛ", value: "am" },
        { label: "Azərbaycanca", value: "az" },
        { label: "Беларуская", value: "be" },
        { label: "Български", value: "bg" },
        { label: "বাংলা", value: "bn" },
        { label: "Bosanski", value: "bs" },
        { label: "Català", value: "ca" },
        { label: "Cebuano", value: "ceb" },
        { label: "Corsu", value: "co" },
        { label: "Čeština", value: "cs" },
        { label: "Cymraeg", value: "cy" },
        { label: "Dansk", value: "da" },
        { label: "Ελληνικά", value: "el" },
        { label: "Esperanto", value: "eo" },
        { label: "Eesti", value: "et" },
        { label: "Euskara", value: "eu" },
        { label: "فارسی", value: "fa" },
        { label: "Suomi", value: "fi" },
        { label: "Fijian", value: "fj" },
        { label: "Frysk", value: "fy" },
        { label: "Gaeilge", value: "ga" },
        { label: "Gàidhlig", value: "gd" },
        { label: "Galego", value: "gl" },
        { label: "ગુજરાતી", value: "gu" },
        { label: "Hausa", value: "ha" },
        { label: "Hawaiian", value: "haw" },
        { label: "עברית", value: "he" },
        { label: "Hrvatski", value: "hr" },
        { label: "Kreyòl Ayisyen", value: "ht" },
        { label: "Magyar", value: "hu" },
        { label: "Հայերեն", value: "hy" },
        { label: "Igbo", value: "ig" },
        { label: "Íslenska", value: "is" },
        { label: "Basa Jawa", value: "jw" },
        { label: "ქართული", value: "ka" },
        { label: "Қазақша", value: "kk" },
        { label: "ភាសាខ្មែរ", value: "km" },
        { label: "ಕನ್ನಡ", value: "kn" },
        { label: "کوردی", value: "ku" },
        { label: "Кыргызча", value: "ky" },
        { label: "Latina", value: "la" },
        { label: "Lëtzebuergesch", value: "lb" },
        { label: "ພາສາລາວ", value: "lo" },
        { label: "Lietuvių", value: "lt" },
        { label: "Latviešu", value: "lv" },
        { label: "Malagasy", value: "mg" },
        { label: "Māori", value: "mi" },
        { label: "Македонски", value: "mk" },
        { label: "മലയാളം", value: "ml" },
        { label: "Монгол", value: "mn" },
        { label: "मराठी", value: "mr" },
        { label: "Bahasa Melayu", value: "ms" },
        { label: "Malti", value: "mt" },
        { label: "Hmong Daw", value: "mww" },
        { label: "မြန်မာဘာသာ", value: "my" },
        { label: "नेपाली", value: "ne" },
        { label: "Norsk", value: "no" },
        { label: "Nyanja", value: "ny" },
        { label: "Otomi", value: "otq" },
        { label: "ਪੰਜਾਬੀ", value: "pa" },
        { label: "Polski", value: "pl" },
        { label: "پښتو", value: "ps" },
        { label: "Română", value: "ro" },
        { label: "سنڌي", value: "sd" },
        { label: "සිංහල", value: "si" },
        { label: "Slovenčina", value: "sk" },
        { label: "Slovenščina", value: "sl" },
        { label: "Samoa", value: "sm" },
        { label: "Shona", value: "sn" },
        { label: "Soomaali", value: "so" },
        { label: "Shqip", value: "sq" },
        { label: "Српски", value: "sr-Cyrl" },
        { label: "Srpski", value: "sr-Latn" },
        { label: "Sesotho", value: "st" },
        { label: "Sunda", value: "su" },
        { label: "Svenska", value: "sv" },
        { label: "Kiswahili", value: "sw" },
        { label: "தமிழ்", value: "ta" },
        { label: "తెలుగు", value: "te" },
        { label: "Тоҷикӣ", value: "tg" },
        { label: "Filipino", value: "tl" },
        { label: "tlhIngan Hol", value: "tlh" },
        { label: "Lea faka-Tonga", value: "to" },
        { label: "Türkçe", value: "tr" },
        { label: "Tahitian", value: "ty" },
        { label: "Українська", value: "uk" },
        { label: "اردو", value: "ur" },
        { label: "Oʻzbekcha", value: "uz" },
        { label: "Xhosa", value: "xh" },
        { label: "יידיש", value: "yi" },
        { label: "Yorùbá", value: "yo" },
        { label: "Yucatec", value: "yua" },
        { label: "粵語", value: "yue" },
        { label: "isiZulu", value: "zu" }
    ]
}