export interface LanguageOption {
    label: string,
    value: string
}

export interface Languages {
    [key: string]: LanguageOption[]
}

export const languages: Languages = {
    baidu: [
        { label: "Auto", value: "auto" },
        { label: "中文", value: "zh" },
        { label: "English", value: "en" },
        { label: "粵語", value: "yue" },
        { label: "文言文", value: "wyw" },
        { label: "日本語", value: "jp" },
        { label: "한국어", value: "kor" },
        { label: "Français", value: "fra" },
        { label: "Español", value: "spa" },
        { label: "ภาษาไทย", value: "th" },
        { label: "العربية", value: "ara" },
        { label: "Русский", value: "ru" },
        { label: "Português", value: "pt" },
        { label: "Deutsch", value: "de" },
        { label: "Italiano", value: "it" },
        { label: "Ελληνικά", value: "el" },
        { label: "Nederlands", value: "nl" },
        { label: "Polski", value: "pl" },
        { label: "Български", value: "bul" },
        { label: "Eesti", value: "est" },
        { label: "Dansk", value: "dan" },
        { label: "Suomi", value: "fin" },
        { label: "Čeština", value: "cs" },
        { label: "Română", value: "rom" },
        { label: "Slovenščina", value: "slo" },
        { label: "Svenska", value: "swe" },
        { label: "Magyar", value: "hu" },
        { label: "繁體中文", value: "cht" },
        { label: "Tiếng Việt", value: "vie" }
    ],
    youdao: [
        { label: "العربية", value: "ar" },
        { label: "Deutsch", value: "de" },
        { label: "English", value: "en" },
        { label: "Español", value: "es" },
        { label: "Français", value: "fr" },
        { label: "हिन्दी", value: "hi" },
        { label: "Bahasa Indonesia", value: "id" },
        { label: "Italiano", value: "it" },
        { label: "日本語", value: "ja" },
        { label: "한국어", value: "ko" },
        { label: "Nederlands", value: "nl" },
        { label: "Português", value: "pt" },
        { label: "Русский", value: "ru" },
        { label: "ภาษาไทย", value: "th" },
        { label: "Tiếng Việt", value: "vi" },
        { label: "简体中文", value: "zh-CHS" },
        { label: "繁體中文", value: "zh-CHT" },
        { label: "Afrikaans", value: "af" },
        { label: "አማርኛ", value: "am" },
        { label: "Azərbaycanca", value: "az" },
        { label: "Беларуская", value: "be" },
        { label: "Български", value: "bg" },
        { label: "বাংলা", value: "bn" },
        { label: "Bosanski", value: "bs" },
        { label: "Català", value: "ca" },
        { label: "Cebuano", value: "ceb" },
        { label: "Corsu", value: "co" },
        { label: "Čeština", value: "cs" },
        { label: "Cymraeg", value: "cy" },
        { label: "Dansk", value: "da" },
        { label: "Ελληνικά", value: "el" },
        { label: "Esperanto", value: "eo" },
        { label: "Eesti", value: "et" },
        { label: "Euskara", value: "eu" },
        { label: "فارسی", value: "fa" },
        { label: "Suomi", value: "fi" },
        { label: "Fijian", value: "fj" },
        { label: "Frysk", value: "fy" },
        { label: "Gaeilge", value: "ga" },
        { label: "Gàidhlig", value: "gd" },
        { label: "Galego", value: "gl" },
        { label: "ગુજરાતી", value: "gu" },
        { label: "Hausa", value: "ha" },
        { label: "Hawaiian", value: "haw" },
        { label: "עברית", value: "he" },
        { label: "Hrvatski", value: "hr" },
        { label: "Kreyòl Ayisyen", value: "ht" },
        { label: "Magyar", value: "hu" },
        { label: "Հայերեն", value: "hy" },
        { label: "Igbo", value: "ig" },
        { label: "Íslenska", value: "is" },
        { label: "Basa Jawa", value: "jw" },
        { label: "ქართული", value: "ka" },
        { label: "Қазақша", value: "kk" },
        { label: "ភាសាខ្មែរ", value: "km" },
        { label: "ಕನ್ನಡ", value: "kn" },
        { label: "کوردی", value: "ku" },
        { label: "Кыргызча", value: "ky" },
        { label: "Latina", value: "la" },
        { label: "Lëtzebuergesch", value: "lb" },
        { label: "ພາສາລາວ", value: "lo" },
        { label: "Lietuvių", value: "lt" },
        { label: "Latviešu", value: "lv" },
        { label: "Malagasy", value: "mg" },
        { label: "Māori", value: "mi" },
        { label: "Македонски", value: "mk" },
        { label: "മലയാളം", value: "ml" },
        { label: "Монгол", value: "mn" },
        { label: "मराठी", value: "mr" },
        { label: "Bahasa Melayu", value: "ms" },
        { label: "Malti", value: "mt" },
        { label: "Hmong Daw", value: "mww" },
        { label: "မြန်မာဘာသာ", value: "my" },
        { label: "नेपाली", value: "ne" },
        { label: "Norsk", value: "no" },
        { label: "Nyanja", value: "ny" },
        { label: "Otomi", value: "otq" },
        { label: "ਪੰਜਾਬੀ", value: "pa" },
        { label: "Polski", value: "pl" },
        { label: "پښتو", value: "ps" },
        { label: "Română", value: "ro" },
        { label: "سنڌي", value: "sd" },
        { label: "සිංහල", value: "si" },
        { label: "Slovenčina", value: "sk" },
        { label: "Slovenščina", value: "sl" },
        { label: "Samoa", value: "sm" },
        { label: "Shona", value: "sn" },
        { label: "Soomaali", value: "so" },
        { label: "Shqip", value: "sq" },
        { label: "Српски", value: "sr-Cyrl" },
        { label: "Srpski", value: "sr-Latn" },
        { label: "Sesotho", value: "st" },
        { label: "Sunda", value: "su" },
        { label: "Svenska", value: "sv" },
        { label: "Kiswahili", value: "sw" },
        { label: "தமிழ்", value: "ta" },
        { label: "తెలుగు", value: "te" },
        { label: "Тоҷикӣ", value: "tg" },
        { label: "Filipino", value: "tl" },
        { label: "tlhIngan Hol", value: "tlh" },
        { label: "Lea faka-Tonga", value: "to" },
        { label: "Türkçe", value: "tr" },
        { label: "Tahitian", value: "ty" },
        { label: "Українська", value: "uk" },
        { label: "اردو", value: "ur" },
        { label: "Oʻzbekcha", value: "uz" },
        { label: "Xhosa", value: "xh" },
        { label: "יידיש", value: "yi" },
        { label: "Yorùbá", value: "yo" },
        { label: "Yucatec", value: "yua" },
        { label: "粵語", value: "yue" },
        { label: "isiZulu", value: "zu" }
    ],
    aliyun: [
        {"label":"Абхазский","value":"ab"},
        {"label":"Shqip","value":"sq"},
        {"label":"Akan","value":"ak"},
        {"label":"العربية","value":"ar"},
        {"label":"Aragonés","value":"an"},
        {"label":"አማርኛ","value":"am"},
        {"label":"অসমীয়া","value":"as"},
        {"label":"Azərbaycanca","value":"az"},
        {"label":"Asturianu","value":"ast"},
        {"label":"Náhuatl","value":"nch"},
        {"label":"Eʋe","value":"ee"},
        {"label":"Aymara","value":"ay"},
        {"label":"Gaeilge","value":"ga"},
        {"label":"Eesti","value":"et"},
        {"label":"Ojibwe","value":"oj"},
        {"label":"Occitan","value":"oc"},
        {"label":"ଓଡ଼ିଆ","value":"or"},
        {"label":"Afaan Oromoo","value":"om"},
        {"label":"Ирон","value":"os"},
        {"label":"Tok Pisin","value":"tpi"},
        {"label":"Башҡортса","value":"ba"},
        {"label":"Euskara","value":"eu"},
        {"label":"Беларуская","value":"be"},
        {"label":"Tamazight","value":"ber"},
        {"label":"Bamanankan","value":"bm"},
        {"label":"Pangasinan","value":"pag"},
        {"label":"Български","value":"bg"},
        {"label":"Sámegiella","value":"se"},
        {"label":"Bemba","value":"bem"},
        {"label":"Blin","value":"byn"},
        {"label":"Bislama","value":"bi"},
        {"label":"بلوچی","value":"bal"},
        {"label":"Polski","value":"pl"},
        {"label":"Íslenska","value":"is"},
        {"label":"Bosanski","value":"bs"},
        {"label":"فارسی","value":"fa"},
        {"label":"भोजपुरी","value":"bho"},
        {"label":"Brezhoneg","value":"br"},
        {"label":"Chamoru","value":"ch"},
        {"label":"Chavacano","value":"cbk"},
        {"label":"Чӑвашла","value":"cv"},
        {"label":"Xitsonga","value":"ts"},
        {"label":"Татарча","value":"tt"},
        {"label":"Dansk","value":"da"},
        {"label":"ရှမ်း","value":"shn"},
        {"label":"Tetum","value":"tet"},
        {"label":"Deutsch","value":"de"},
        {"label":"Niedersächsisch","value":"nds"},
        {"label":"Scots","value":"sco"},
        {"label":"ދިވެހި","value":"dv"},
        {"label":"Kam","value":"kdx"},
        {"label":"Kadazan Dusun","value":"dtp"},
        {"label":"Русский","value":"ru"},
        {"label":"Føroyskt","value":"fo"},
        {"label":"Français","value":"fr"},
        {"label":"संस्कृतम्","value":"sa"},
        {"label":"Filipino","value":"fil"},
        {"label":"Vosa Vakaviti","value":"fj"},
        {"label":"Suomi","value":"fi"},
        {"label":"Furlan","value":"fur"},
        {"label":"Fur","value":"fvr"},
        {"label":"Kikongo","value":"kg"},
        {"label":"ភាសាខ្មែរ","value":"km"},
        {"label":"Náhuatl","value":"ngu"},
        {"label":"Kalaallisut","value":"kl"},
        {"label":"ქართული","value":"ka"},
        {"label":"Gronings","value":"gos"},
        {"label":"ગુજરાતી","value":"gu"},
        {"label":"Guaraní","value":"gn"},
        {"label":"Қазақша","value":"kk"},
        {"label":"Kreyòl Ayisyen","value":"ht"},
        {"label":"한국어","value":"ko"},
        {"label":"Hausa","value":"ha"},
        {"label":"Nederlands","value":"nl"},
        {"label":"Crnogorski","value":"cnr"},
        {"label":"Hupa","value":"hup"},
        {"label":"Gilbertese","value":"gil"},
        {"label":"Ikirundi","value":"rn"},
        {"label":"K'iche'","value":"quc"},
        {"label":"Кыргызча","value":"ky"},
        {"label":"Galego","value":"gl"},
        {"label":"Català","value":"ca"},
        {"label":"Čeština","value":"cs"},
        {"label":"Taqbaylit","value":"kab"},
        {"label":"ಕನ್ನಡ","value":"kn"},
        {"label":"Kanuri","value":"kr"},
        {"label":"Kaszubski","value":"csb"},
        {"label":"Khasi","value":"kha"},
        {"label":"Kernowek","value":"kw"},
        {"label":"isiXhosa","value":"xh"},
        {"label":"Corsu","value":"co"},
        {"label":"Mvskoke","value":"mus"},
        {"label":"Къырымтатарджа","value":"crh"},
        {"label":"tlhIngan Hol","value":"tlh"},
        {"label":"Hrvatski","value":"hbs"},
        {"label":"Quechua","value":"qu"},
        {"label":"कश्मीरी","value":"ks"},
        {"label":"کوردی","value":"ku"},
        {"label":"Latina","value":"la"},
        {"label":"Latgalīšu","value":"ltg"},
        {"label":"Latviešu","value":"lv"},
        {"label":"ພາສາລາວ","value":"lo"},
        {"label":"Lietuvių","value":"lt"},
        {"label":"Limburgs","value":"li"},
        {"label":"Lingala","value":"ln"},
        {"label":"Luganda","value":"lg"},
        {"label":"Lëtzebuergesch","value":"lb"},
        {"label":"Русиньскый","value":"rue"},
        {"label":"Kinyarwanda","value":"rw"},
        {"label":"Română","value":"ro"},
        {"label":"Romansh","value":"rm"},
        {"label":"Romani","value":"rom"},
        {"label":"Lojban","value":"jbo"},
        {"label":"Malagasy","value":"mg"},
        {"label":"Gaelg","value":"gv"},
        {"label":"Malti","value":"mt"},
        {"label":"मराठी","value":"mr"},
        {"label":"മലയാളം","value":"ml"},
        {"label":"Bahasa Melayu","value":"ms"},
        {"label":"Марийский","value":"chm"},
        {"label":"Македонски","value":"mk"},
        {"label":"Kajin M̧ajeļ","value":"mh"},
        {"label":"Kekchí","value":"kek"},
        {"label":"मैथिली","value":"mai"},
        {"label":"Morisien","value":"mfe"},
        {"label":"Te Reo Māori","value":"mi"},
        {"label":"Монгол","value":"mn"},
        {"label":"বাংলা","value":"bn"},
        {"label":"မြန်မာဘာသာ","value":"my"},
        {"label":"Hmong","value":"hmn"},
        {"label":"Umbundu","value":"umb"},
        {"label":"Navajo","value":"nv"},
        {"label":"Afrikaans","value":"af"},
        {"label":"नेपाली","value":"ne"},
        {"label":"Niuean","value":"niu"},
        {"label":"Norsk","value":"no"},
        {"label":"Pam","value":"pmn"},
        {"label":"Papiamentu","value":"pap"},
        {"label":"ਪੰਜਾਬੀ","value":"pa"},
        {"label":"Português","value":"pt"},
        {"label":"پښتو","value":"ps"},
        {"label":"Nyanja","value":"ny"},
        {"label":"Twi","value":"tw"},
        {"label":"ᏣᎳᎩ","value":"chr"},
        {"label":"日本語","value":"ja"},
        {"label":"Svenska","value":"sv"},
        {"label":"Gagana Samoa","value":"sm"},
        {"label":"Sängö","value":"sg"},
        {"label":"සිංහල","value":"si"},
        {"label":"Hornjoserbsce","value":"hsb"},
        {"label":"Esperanto","value":"eo"},
        {"label":"Slovenščina","value":"sl"},
        {"label":"Kiswahili","value":"sw"},
        {"label":"Soomaali","value":"so"},
        {"label":"Slovenčina","value":"sk"},
        {"label":"Tagalog","value":"tl"},
        {"label":"Тоҷикӣ","value":"tg"},
        {"label":"Tahitian","value":"ty"},
        {"label":"తెలుగు","value":"te"},
        {"label":"தமிழ்","value":"ta"},
        {"label":"ภาษาไทย","value":"th"},
        {"label":"Lea faka-Tonga","value":"to"},
        {"label":"Tonga","value":"toi"},
        {"label":"ትግርኛ","value":"ti"},
        {"label":"Tuvaluan","value":"tvl"},
        {"label":"Тыва дыл","value":"tyv"},
        {"label":"Türkçe","value":"tr"},
        {"label":"Türkmençe","value":"tk"},
        {"label":"Walloon","value":"wa"},
        {"label":"Waray","value":"war"},
        {"label":"Cymraeg","value":"cy"},
        {"label":"Tshivenda","value":"ve"},
        {"label":"Volapük","value":"vo"},
        {"label":"Wolof","value":"wo"},
        {"label":"Удмурт","value":"udm"},
        {"label":"اردو","value":"ur"},
        {"label":"Oʻzbekcha","value":"uz"},
        {"label":"Español","value":"es"},
        {"label":"Interlingue","value":"ie"},
        {"label":"Frysk","value":"fy"},
        {"label":"Ślůnski","value":"szl"},
        {"label":"עברית","value":"he"},
        {"label":"Hiligaynon","value":"hil"},
        {"label":"ʻŌlelo Hawaiʻi","value":"haw"},
        {"label":"Ελληνικά","value":"el"},
        {"label":"Lingua Franca Nova","value":"lfn"},
        {"label":"سنڌي","value":"sd"},
        {"label":"Magyar","value":"hu"},
        {"label":"Shona","value":"sn"},
        {"label":"Cebuano","value":"ceb"},
        {"label":"ܣܘܪܝܝܐ","value":"syr"},
        {"label":"Basa Sunda","value":"su"},
        {"label":"Հայերեն","value":"hy"},
        {"label":"Bahasa Aceh","value":"ace"},
        {"label":"Iban","value":"iba"},
        {"label":"Igbo","value":"ig"},
        {"label":"Ido","value":"io"},
        {"label":"Ilokano","value":"ilo"},
        {"label":"Inuktitut","value":"iu"},
        {"label":"Italiano","value":"it"},
        {"label":"ייִדיש","value":"yi"},
        {"label":"Interlingua","value":"ia"},
        {"label":"हिन्दी","value":"hi"},
        {"label":"Bahasa Indonesia","value":"id"},
        {"label":"ГӀалгӀай","value":"inh"},
        {"label":"English","value":"en"},
        {"label":"Yorùbá","value":"yo"},
        {"label":"Tiếng Việt","value":"vi"},
        {"label":"Zazaki","value":"zza"},
        {"label":"Basa Jawa","value":"jv"},
        {"label":"中文","value":"zh"},
        {"label":"繁體中文","value":"zh-tw"},
        {"label":"粵語","value":"yue"},
        {"label":"isiZulu","value":"zu"}
    ]

}